{
 "title": "LBaaS System Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "HTTP Request Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(http_requests_total[1m])", "legendFormat": "{{job}} - {{endpoint}}" }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "http_request_duration_seconds_sum / http_request_duration_seconds_count",
     "legendFormat": "{{job}} - {{endpoint}}"
    }
   ]
  },
  {
   "title": "HTTP Status Codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job, status_code) (rate(http_requests_total[1m]))",
     "legendFormat": "{{job}} - {{status_code}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "{{job}}" }
   ]
  }
 ]
}