global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api'
    static_configs:
      - targets: ['api:8000']
  - job_name: 'business'
    static_configs:
      - targets: ['business:8001']
  - job_name: 'integration'
    static_configs:
      - targets: ['integration:8002']
  - job_name: 'mock-servicenow'
    static_configs:
      - targets: ['mock-servicenow:8010']
  - job_name: 'mock-bluecat'
    static_configs:
      - targets: ['mock-bluecat:8011']
  - job_name: 'mock-cert'
    static_configs:
      - targets: ['mock-cert:8012']
